{
 "title": "Dell R730 物理服务器iDRAC SNMP监控面板",
 "description": "戴尔物理服务器iDRAC监控面板",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "区域", "query": { "query": "label_values(snmp_up,region)" } },
   {
    "name": "role",
    "label": "角色",
    "query": {
     "query": "label_values(snmp_up{region=~\"$region\"},role)"
    }
   },
   {
    "name": "brand",
    "label": "品牌",
    "query": {
     "query": "label_values(snmp_up{role=~\"$role\", region=~\"$region\"},brand)"
    }
   },
   {
    "name": "device_ip",
    "label": "物理机IP",
    "query": {
     "query": "label_values(snmp_up{region=~\"$region\", role=~\"$role\", brand=~\"$brand\"},device_ip)"
    }
   },
   {
    "name": "total",
    "label": "服务器总数",
    "query": {
     "query": "query_result(count(snmp_up{region=~\"$region\",role=~\"$role\",brand=~\"$brand\"}))"
    }
   },
   { "name": "Filters", "label": "筛选" }
  ]
 },
 "panels": [
  { "title": "系统信息：总数【$total】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统信息",
   "type": "table",
   "description": "服务器系统基础信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "snmp_dell_system_id{region=~\"$region\", role=~\"$role\", brand=~\"$brand\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_icmp_up{region=~\"$region\", role=~\"$role\", brand=~\"$brand\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "组件状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "系统启动时间（天）",
   "type": "stat",
   "description": "戴尔物理服务器系统启动时间信息",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_system_power_uptime{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"} / 3600 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统电源状态",
   "type": "stat",
   "description": "戴尔物理服务器全局系统电源状态信息",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_system_power_state{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局系统状态",
   "type": "stat",
   "description": "戴尔物理服务器全局系统状态信息",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_glob_system_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "全局存储状态",
   "type": "stat",
   "description": "戴尔物理服务器全局存储状态信息",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_global_storage_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BIOS状态",
   "type": "table",
   "description": "戴尔物理服务器设备BIOS状态信息",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "snmp_dell_bios_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "事件日志条目数",
   "type": "timeseries",
   "description": "戴尔物理服务器事件日志中的条目数",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_num_event_log{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "{{device_ip}}"
    }
   ]
  },
  {
   "title": "系统使用功率",
   "type": "timeseries",
   "description": "物理机使用功率",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "snmp_dell_amperage_reading{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "{{power_location_name}}"
    }
   ]
  },
  {
   "title": "LCD状态",
   "type": "table",
   "description": "戴尔物理服务器设备LCD状态信息",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "snmp_dell_intrusion_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "物理机当前使用功率",
   "type": "stat",
   "description": "物理机当前使用功率",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_amperage_reading{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "{{power_location_name}}"
    }
   ]
  },
  {
   "title": "Raid状态信息",
   "type": "table",
   "description": "戴尔物理服务器设备Raid状态信息",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "snmp_dell_virtual_disk_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_virtual_disk_size{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "风扇状态",
   "type": "table",
   "description": "戴尔物理服务器风扇状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "snmp_dell_cooling_device_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_cooling_rpm{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "固件状态",
   "type": "table",
   "description": "戴尔物理服务器固件状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "snmp_dell_firmware_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "侵入设备状态",
   "type": "table",
   "description": "戴尔物理服务器侵入设备状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "snmp_dell_intrusion_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "电源设备状态",
   "type": "table",
   "description": "戴尔物理服务器电源状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "snmp_dell_power_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_power_max_inputvlo{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_power_current_inputvlo{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "温度传感器状态",
   "type": "table",
   "description": "戴尔物理服务器温度传感器状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "snmp_dell_temperature_probe_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_temperature_value{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"} / 10",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_temperature_threshold{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI设备状态",
   "type": "table",
   "description": "戴尔物理服务器PCI设备状态信息",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "snmp_dell_pci_device_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "内存信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "内存状态",
   "type": "stat",
   "description": "戴尔物理服务器内存状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_mem_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "{{mem_fqdd}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "table",
   "description": "戴尔物理服务器内存信息",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_mem_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "硬盘信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "硬盘状态",
   "type": "stat",
   "description": "戴尔物理服务器硬盘状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_dell_physical_disk_self_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "{{physical_disk_name}}"
    }
   ]
  },
  {
   "title": "硬盘状态信息",
   "type": "table",
   "description": "戴尔物理服务器硬盘状态信息",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_physical_disk_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "硬盘信息",
   "type": "table",
   "description": "戴尔物理服务器硬盘信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_physical_disk_bus_type{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "硬盘速率信息",
   "type": "table",
   "description": "戴尔物理服务器硬盘速率信息",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_physical_disk_usage{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "网卡信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "网卡信息",
   "type": "table",
   "description": "戴尔物理服务器网卡信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_network_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "控制器信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "存储控制器状态",
   "type": "table",
   "description": "戴尔物理服务器存储控制器信息",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_contr_comp_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_rollup_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "存储控制器性能信息",
   "type": "table",
   "description": "戴尔物理服务器存储控制器性能信息",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_contr_cache_size{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_security_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_balance_mode{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_max_speed{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "存储控制器速率信息",
   "type": "table",
   "description": "戴尔物理服务器存储控制器速率信息",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_contr_rebuild_rate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_reson_rate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_patrol_rate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_bgi_rate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snmp_dell_contr_check_rate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FRU信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRU信息",
     "type": "table",
     "description": "戴尔物理服务器FRU信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "snmp_dell_fru_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "PCI组件信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "PCI信息",
   "type": "table",
   "description": "戴尔物理服务器PCI信息",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_dell_pci_device_status{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", device_ip=\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}