apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s: nginx-exporter
  template:
    metadata:
      labels:
        k8s: nginx-exporter
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.9.0
          command:
            - 'nginx-prometheus-exporter'
          args:
            - '-nginx.scrape-uri=http://172.27.0.3:8080/stub_status'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    k8s: nginx-exporter
spec:
  type: ClusterIP
  ports:
  - name: nginx-api
    port: 9113
    protocol: TCP
  selector:
    k8s: nginx-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    k8s: nginx-exporter
spec:
  endpoints:
    - interval: 10s
      port: nginx-api
      scheme: http
  selector:
    matchLabels:
      k8s: nginx-exporter
  namespaceSelector:
    matchNames:
    - monitoring
