apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  strategy: {}
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - image: oliver006/redis_exporter:latest
        name: redis-exporter
        args: ["-redis.addr", "redis://172.27.0.3:6379", "-redis.password", "Test@123"]
        ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    k8s-app: redis-exporter
spec:
  ports:
  - port: 9121
    protocol: TCP
    name: redis
  selector:
    app: redis-exporter
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    k8s-app: redis-exporter
spec:
  endpoints:
    - interval: 10s
      port: redis
      scheme: http
  selector:
    matchLabels:
      k8s-app: redis-exporter
  namespaceSelector:
    matchNames:
    - monitoring
