global:
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: 'from_user@qq.com'
  smtp_auth_username: 'from_user@qq.com'
  smtp_auth_password: 'from_user_key'
  smtp_require_tls: false

templates:
  - '/etc/alertmanager/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: email

receivers:
- name: 'email'
  email_configs:
  - to: 'to_user@qq.com'
    send_resolved: true
    headers:
      subject: "{{ .CommonLabels.subject }}"
    html: '{{ template "email.html" . }}'

inhibit_rules:
 - source_match:
     severity: 'critical'
   target_match:
     severity: 'warning'
   equal: ['alertname', 'dev', 'instance']
