groups:
- name: Prometheus alert
  rules:
  - alert: 服务告警
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "服务异常，实例: {{ $labels.instance }}"
      description: "{{ $labels.job }} 服务已关闭"

#- name: Nginx alert
#  rules:
#  - alert: Nginx服务异常
#    expr: nginx_up == 0
#    for: 30s
#    labels:
#      severity: critical
#    annotations:
#      summary: "Nginx服务异常，实例: {{ $labels.instance }}"
#      description: "Nginx服务未响应"
