# 全局配置
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# 报警(触发器)配置
rule_files:
  - "alert.yml"

# 搜刮配置
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    scrape_interval: 15s
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        instance: Prometheus服务器 

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        instance: Prometheus服务器

  - job_name: 'pushgateway'
    scrape_interval: 15s
    static_configs:
    - targets: ['pushgateway:9091']

  # docker run -d --name elasticsearch_exporter -p 9114:9114 --restart always quay.io/prometheuscommunity/elasticsearch-exporter:latest --es.uri=http://elastic:xxxx@172.27.0.3:9200
  - job_name: 'es'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.27.0.3:9114']
      labels:
        instance: es服务器

  # docker run --name nginx-exporter --restart always -d -p 9113:9113 -e NGINX_SCRAPE_URI=http://172.27.0.3/stub_status nginx/nginx-prometheus-exporter
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.27.0.3:9113']
      labels:
        instance: nginx服务器
