# 全局配置
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# 报警(触发器)配置
rule_files:
  - "alert.yml"

# 搜刮配置
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    scrape_interval: 15s
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        instance: Prometheus服务器 

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        instance: Prometheus服务器

  - job_name: 'pushgateway'
    scrape_interval: 15s
    static_configs:
    - targets: ['pushgateway:9091']

  # docker run -d --name elasticsearch_exporter -p 9114:9114 --restart always quay.io/prometheuscommunity/elasticsearch-exporter:latest --es.uri=http://elastic:xxxx@172.27.0.3:9200
  - job_name: 'es'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.27.0.3:9114']
      labels:
        instance: es服务器


  #[root@172 ~]# cat default.conf | grep -A 3 "stub_status"
  #  location /stub_status {
  #      stub_status;
  #      allow 127.0.0.1;
  #  }
  # docker run --name nginx-exporter --restart always -d -p 9113:9113 nginx/nginx-prometheus-exporter --nginx.scrape-uri=http://172.27.0.3/stub_status
  - job_name: 'nginx'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.27.0.3:9113']
      labels:
        instance: nginx服务器


  #docker run -d --name redis_exporter   -p 9121:9121   -e REDIS_ADDR=redis://:123456@172.27.0.3:6379   -e REDIS_PASSWORD=123456  oliver006/redis_exporter:v1.38.0
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
    - targets: ['172.27.0.3:9121']
      labels:
        instance: redis服务器
