global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# 报警(触发器)配置
rule_files:
  - "alert.yml"

# 搜刮配置
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    scrape_interval: 15s
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        instance: Prometheus服务器 

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        instance: Prometheus服务器

  - job_name: 'pushgateway'
    scrape_interval: 15s
    static_configs:
    - targets: ['pushgateway:9091']

#  - job_name: 'nginx'
#    scrape_interval: 15s
#    static_configs:
#    - targets: ['172.27.0.3:9113']  可以用docker run -dp 9113:9113 --name nginx-exporter nginx/nginx-prometheus-exporter:0.9.0 -nginx.scrape-uri=http://172.27.0.3/stub_status 探测nginx服务
#      labels:
#        instance: Nginx服务器
